version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql_server_container
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=QuachNamLuong1!
    deploy:
      resources:
        limits:
          memory: 1g
          cpus: '0.2'
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - sql-network

volumes:
  sqlserver_data:

networks:
  sql-network:
    driver: bridge
